# Generated by Codex on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grok", "0004_grokaccount_auth_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grokaccount",
            name="access_token_valid",
            field=models.BooleanField(default=False, verbose_name="AccessToken 可用"),
        ),
        migrations.AddField(
            model_name="grokaccount",
            name="session_token_valid",
            field=models.BooleanField(default=False, verbose_name="SessionToken 可用"),
        ),
        migrations.AddField(
            model_name="grokaccount",
            name="last_check_at",
            field=models.IntegerField(blank=True, null=True, verbose_name="最近诊断时间"),
        ),
        migrations.AddField(
            model_name="grokaccount",
            name="last_error",
            field=models.TextField(blank=True, null=True, verbose_name="最近诊断错误"),
        ),
    ]
