# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grok", "0006_grokaccount_extra_cookies"),
    ]

    operations = [
        migrations.AddField(
            model_name="grokaccount",
            name="proxy_node_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="代理节点"),
        ),
    ]
